apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  volumeClaimTemplate:
    resources:
      requests:
        storage: 10Gi
    accessModes:
      - ReadWriteOnce

  replicas: 3

  galera:
    enabled: true

  service:
    type: ClusterIP

  primaryService:
    type: ClusterIP

  secondaryService:
    type: ClusterIP