apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  rootUser: cm9vdA== # base64 for 'root'
  rootHost: JQ== # base64 for '%'
  rootPassword: IXlWZWd6VmJIRlpudmshdjdRYlY3cXloOQ== # base64 for '!yVegzVbHFZnvk!v7QbV7qyh9'
